import { Numans, Raleway, } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

import Header from "@/components/header";
import Footer from "@/components/footer";

const myriadPro = localFont({
  src: [
    {
      path: '../fonts/myriad-pro/MYRIADPRO-REGULAR.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/myriad-pro/MYRIADPRO-BOLD.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../fonts/myriad-pro/MYRIADPRO-BOLDIT.otf',
      weight: '700',
      style: 'italic',
    },
    {
      path: '../fonts/myriad-pro/MYRIADPRO-BOLDCOND.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../fonts/myriad-pro/MYRIADPRO-BOLDCONDIT.otf',
      weight: '700',
      style: 'italic',
    },
    {
      path: '../fonts/myriad-pro/MYRIADPRO-COND.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/myriad-pro/MYRIADPRO-CONDIT.otf',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../fonts/myriad-pro/MyriadPro-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../fonts/myriad-pro/MYRIADPRO-SEMIBOLD.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../fonts/myriad-pro/MYRIADPRO-SEMIBOLDIT.otf',
      weight: '600',
      style: 'italic',
    },
  ],
  variable: '--font-myriad',
  display: 'swap',
})

const numans = Numans({
  variable: "--font-numans",
  weight: "400",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

export const metadata = {
  title: "MRCare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${numans.variable} ${raleway.variable} ${myriadPro.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
